# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nicaragua_import',
            name='codigo_barrio',
        ),
        migrations.RemoveField(
            model_name='nicaragua_import',
            name='codigo_departamento',
        ),
        migrations.RemoveField(
            model_name='nicaragua_import',
            name='codigo_municipio',
        ),
    ]
