# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='zonas',
            field=models.ManyToManyField(blank=True, null=True, to='dtracking.Zona'),
        ),
    ]
