# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de solicitud'),
        ),
    ]
