# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-29 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='observaciones_cotizacion',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='observaciones en la cotizaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='observaciones',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
