# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipogestion',
            name='prefijo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='destinatario',
            field=models.CharField(max_length=125, null=True, verbose_name='Cliente'),
        ),
    ]
