# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-30 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtracking', '0002_auto_20170929_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='armador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestion_armador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gestion',
            name='ficha_inspeccion',
            field=models.FileField(blank=True, null=True, upload_to='fichas'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='informe_final',
            field=models.FileField(blank=True, null=True, upload_to='fichas'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='revizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtracking.Perito', verbose_name='perito'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='tipo_gestion',
            field=models.ManyToManyField(blank=True, to='dtracking.TipoGestion'),
        ),
    ]
