# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0002_auto_20171009_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='barra',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='C\xf3digo de avaluo'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='direccion',
            field=models.TextField(max_length=255, null=True, verbose_name='Ubicacion del bien a valuar'),
        ),
    ]
