# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-30 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0003_auto_20170930_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_gestion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
