# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0004_gestion_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='identificacion',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Identificaci\xf3n'),
        ),
    ]
