# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0004_auto_20170930_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtracking.Barrio'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtracking.Zona'),
        ),
        migrations.AlterField(
            model_name='log_gestion',
            name='estado',
            field=models.CharField(choices=[('RECEPCIONADO', 'RECEPCIONADO'), ('ASIGNADO A EVALUADOR', 'ASIGNADO A EVALUADOR'), ('LEVANTAMIENTO REALIZADO', 'LEVANTAMIENTO REALIZADO'), ('EN REVISION FINAL DE INFORME', 'EN REVISION FINAL DE INFORME'), ('TERMINADO', 'TERMINADO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='log_gestion',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
