# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-02 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0005_auto_20170930_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='direccion',
            field=models.TextField(max_length=255, null=True, verbose_name='Ubicacion del bien a avaluar'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='valor',
            field=models.FloatField(blank=True, null=True, verbose_name='precio del avaluo ya con iva'),
        ),
    ]
