# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0005_auto_20171106_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='fecha_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='dias',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='dias extras para el armado'),
        ),
    ]
