# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0005_auto_20170419_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='identificacion',
            field=models.CharField(max_length=25, null=True, verbose_name='Itentificacion'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='barra',
            field=models.CharField(max_length=65, null=True, verbose_name='codigo de gestion'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log_gestion',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
