# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0006_auto_20170420_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='referencia',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Referencia Bancaria'),
        ),
    ]
