# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-02 21:43
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0006_auto_20171002_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipogestion',
            name='color',
            field=colorfield.fields.ColorField(default='ffffff', max_length=10),
        ),
    ]
