# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtracking', '0007_auto_20170420_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perito',
                'verbose_name_plural': 'Peritos Valuadores',
            },
        ),
        migrations.AlterModelOptions(
            name='gestion',
            options={'verbose_name_plural': 'Aval\xfaos'},
        ),
        migrations.AlterModelOptions(
            name='gestor',
            options={'verbose_name': 'Perito', 'verbose_name_plural': 'Peritos de Campo'},
        ),
        migrations.AlterModelOptions(
            name='tipogestion',
            options={'verbose_name_plural': 'tipos de aval\xfaos'},
        ),
        migrations.AddField(
            model_name='gestion',
            name='fecha_asignacion_valuador',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='status_gestion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='valuador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perito_valuador', to=settings.AUTH_USER_MODEL, verbose_name='perito valuador'),
        ),
        migrations.AlterField(
            model_name='detallegestion',
            name='tipo',
            field=models.CharField(choices=[('input', 'input'), ('radio', 'radio'), ('textarea', 'textarea'), ('combobox', 'combobox'), ('checkbox', 'checkbox'), ('foto', 'foto'), ('multi foto', 'multi foto'), ('firma', 'firma')], max_length=25, verbose_name='tipo de campo'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='barra',
            field=models.CharField(max_length=65, null=True, verbose_name='codigo de aval\xfao'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perito_de_campo', to=settings.AUTH_USER_MODEL, verbose_name='perito de campo'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='tipo_gestion',
            field=models.ManyToManyField(blank=True, to='dtracking.TipoGestion'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='zonas',
            field=models.ManyToManyField(blank=True, to='dtracking.Zona'),
        ),
    ]
