# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-02 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0007_tipogestion_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direcci\xf3n de env\xedo'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, default='12.129239891689053,-86.26631538391109', max_length=42, null=True),
        ),
    ]
