# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0008_auto_20170504_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perito',
            name='user',
        ),
        migrations.DeleteModel(
            name='Perito',
        ),
    ]
