# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0008_auto_20171002_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipogestion',
            options={'ordering': ['prefijo'], 'verbose_name': 'tipo de avaluo', 'verbose_name_plural': 'tipos de avaluos'},
        ),
        migrations.AlterField(
            model_name='gestion',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtracking.Departamento'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='identificacion',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Itentificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtracking.Municipio'),
        ),
    ]
