# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0008_auto_20171212_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='new_banco',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='new_ejecutivo',
        ),
        migrations.AddField(
            model_name='gestion',
            name='banco_sucursal',
            field=models.CharField(blank=True, help_text='temporal', max_length=100, null=True, verbose_name='Sucursal bancaria'),
        ),
    ]
