# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0009_auto_20171212_0503'),
        ('dtracking', '0007_auto_20171211_2011'),
    ]

    operations = [
    ]
