# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0009_auto_20170505_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestion',
            options={'verbose_name_plural': 'gestiones'},
        ),
        migrations.AlterModelOptions(
            name='gestor',
            options={'verbose_name_plural': 'Evaluadores'},
        ),
        migrations.AlterModelOptions(
            name='tipogestion',
            options={'verbose_name_plural': 'tipos de gestiones'},
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='fecha_asignacion_valuador',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='valuador',
        ),
        migrations.AlterField(
            model_name='gestion',
            name='barra',
            field=models.CharField(max_length=65, null=True, verbose_name='codigo de gestion'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='status_gestion',
            field=models.CharField(choices=[('RECEPCIONADO', 'RECEPCIONADO'), ('ASIGNADO A EVALUADOR', 'ASIGNADO A EVALUADOR'), ('LEVANTAMIENTO REALIZADO', 'LEVANTAMIENTO REALIZADO'), ('EN REVISION FINAL DE INFORME', 'EN REVISION FINAL DE INFORME'), ('TERMINADO', 'TERMINADO')], default='RECEPCIONADO', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='tipo_gestion',
            field=models.ManyToManyField(blank=True, null=True, to='dtracking.TipoGestion'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='zonas',
            field=models.ManyToManyField(to='dtracking.Zona'),
        ),
    ]
