# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-03 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtracking', '0009_auto_20171003_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'armadores',
            },
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
        ),
        migrations.AlterModelOptions(
            name='gestor',
            options={'verbose_name': 'perito', 'verbose_name_plural': 'Peritos'},
        ),
        migrations.AlterField(
            model_name='gestion',
            name='armador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestion_armador', to='dtracking.Operaciones'),
        ),
        migrations.AlterField(
            model_name='tipogestion',
            name='tiempo_ejecucion',
            field=models.IntegerField(blank=True, help_text='Tiempo requerido en minutos para el levantamiento de datos de este tipo de avaluo', null=True, verbose_name='tiempo de ejecucion en minutos'),
        ),
        migrations.AddField(
            model_name='armador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
