# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0010_merge_20171212_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='factura',
            field=models.BooleanField(default=False, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='fecha_facturacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='numero',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='N\xfamero'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='control',
            field=models.BooleanField(default=False, verbose_name='control'),
        ),
    ]
