# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0010_auto_20170609_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestion',
            options={'verbose_name_plural': 'Avaluos'},
        ),
        migrations.AddField(
            model_name='gestion',
            name='banco',
            field=models.CharField(blank=True, choices=[('BAMPRO', 'BAMPRO'), ('BANCENTRO', 'BANCENTRO'), ('BAC', 'BAC'), ('BDF', 'BDF'), ('FICOHSA', 'FICOHSA'), ('PROCREDIT', 'PROCREDIT')], max_length=25, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='contacto',
            field=models.CharField(max_length=125, null=True, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='contacto_telefono',
            field=models.CharField(max_length=125, null=True, verbose_name='Telefono del contacto'),
        ),
    ]
