# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0011_auto_20170621_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion_Fin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gestion_Uso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True)),
                ('fin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtracking.Gestion_Fin')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='gestion',
            options={'verbose_name': 'Avaluo', 'verbose_name_plural': 'Avaluos'},
        ),
        migrations.AddField(
            model_name='gestion',
            name='banco_ejecutivo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ejecutivo bancario'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='direccion_envio',
            field=models.TextField(max_length=255, null=True, verbose_name='Direcci\xf3n de env\xedo'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='barra',
            field=models.CharField(max_length=65, null=True, verbose_name='C\xf3digo de avaluo'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='contacto_telefono',
            field=models.CharField(max_length=125, null=True, verbose_name='Tel\xe9fono del contacto'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='direccion',
            field=models.TextField(max_length=255, null=True, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='identificacion',
            field=models.CharField(max_length=25, null=True, verbose_name='Itentificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='referencia',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Referencia bancaria'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='fin_gestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtracking.Gestion_Fin'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='uso_gestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtracking.Gestion_Uso'),
        ),
    ]
