# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-03 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0011_auto_20171003_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='dias',
            field=models.IntegerField(default=0, null=True, verbose_name='dias extras para el armado'),
        ),
    ]
