# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0012_auto_20170621_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestion_fin',
            options={'verbose_name': 'Finalidad de avaluo', 'verbose_name_plural': 'Fines de Avaluo'},
        ),
        migrations.AlterModelOptions(
            name='gestion_uso',
            options={'verbose_name': 'Uso de avaluo', 'verbose_name_plural': 'Usos de Avaluo'},
        ),
        migrations.AlterField(
            model_name='gestion',
            name='contacto',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Tel\xe9fono del contacto'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='direccion_envio',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Direcci\xf3n de env\xedo'),
        ),
    ]
