# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0012_gestion_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ejecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=65, null=True)),
                ('email', models.EmailField(blank=True, max_length=265, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtracking.Banco')),
            ],
        ),
    ]
