# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0013_auto_20170621_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='banco',
            field=models.CharField(blank=True, choices=[('BANPRO', 'BANPRO'), ('BANCENTRO', 'BANCENTRO'), ('BAC', 'BAC'), ('BDF', 'BDF'), ('FICOHSA', 'FICOHSA'), ('PROCREDIT', 'PROCREDIT')], max_length=25, null=True, verbose_name='Banco'),
        ),
    ]
