# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0013_banco_ejecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='new_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtracking.Banco'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='new_ejecutivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtracking.Ejecutivo'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='banco',
            field=models.CharField(blank=True, choices=[('BANPRO', 'BANPRO'), ('BANCENTRO', 'BANCENTRO'), ('BAC', 'BAC'), ('BDF', 'BDF'), ('FICOHSA', 'FICOHSA'), ('PROCREDIT', 'PROCREDIT')], help_text='temporal', max_length=25, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='banco_ejecutivo',
            field=models.CharField(blank=True, help_text='temporal', max_length=100, null=True, verbose_name='Ejecutivo bancario'),
        ),
    ]
