# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0014_auto_20170621_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
