# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0016_auto_20170904_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='fecha_entrega_efectiva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
