# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0018_auto_20170904_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='programacion_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='programacion_incio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
