# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtracking', '0019_auto_20170922_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipogestion',
            name='tiempo_ejecucion',
            field=models.IntegerField(blank=True, help_text='Tiempo maximo requerido para el levantamiento de datos de este tipo de gestion', null=True),
        ),
    ]
