# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-29 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('dtracking', '0021_auto_20170929_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perito',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
        ),
        migrations.AlterModelOptions(
            name='tipogestion',
            options={'verbose_name': 'tipo de avaluo', 'verbose_name_plural': 'tipos de avaluos'},
        ),
        migrations.AlterField(
            model_name='gestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtracking.Perito'),
        ),
        migrations.AlterField(
            model_name='tipogestion',
            name='tiempo_ejecucion',
            field=models.IntegerField(blank=True, help_text='Tiempo requerido en minutos para el levantamiento de datos de este tipo de avaluo', null=True),
        ),
    ]
